import matplotlib.pyplot as plt
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
sales = [15000, 2000, 1000, 2000, 5000, 1000]
plt.figure(figsize=(15, 5))
plt.subplot(131)
plt.plot(months, sales, marker='o')
plt.title('Monthly Sales Prediction (Line Plot)')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.grid(True)
plt.subplot(132)
plt.scatter(months, sales, color='blue', marker='o')
plt.title('Monthly Sales Prediction (Scatter Plot)')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.grid(True)
plt.subplot(133)
plt.bar(months, sales, color='green')
plt.title('Monthly Sales Data (Bar Plot)')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.grid(True)
plt.tight_layout()
plt.show()
